# version: '3.8'
volumes:
  mongodb_data:
    external: true
services:
  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  
  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongodb
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_USERNAME: root
      ME_CONFIG_MONGODB_PASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    restart: always

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    # restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/
      - DATABASE_NAME=mongodb_data
      - WAIT_HOSTS=mongodb:27017
      - CORS_HOST=http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app

  frontend:
    build: 
      context: ./frontend/crash-gab
      dockerfile: Dockerfile
    # restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend/crash-gab:/app

