FROM python:3.12-bookworm as base

# Create non-root user
# RUN useradd -m -u 1000 appuser

# Update wait utility
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.11.0/wait /wait
RUN chmod +x /wait

# Install dependencies
WORKDIR /deps
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Setup app
WORKDIR /app
# USER appuser

# Configurable settings
ENV MODULE_NAME=app.main
ENV VARIABLE_NAME=app
ENV PORT=8000

# Add healthcheck
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
  CMD curl -f http://localhost:${PORT}/health || exit 1

# Run the application
CMD /wait && uvicorn ${MODULE_NAME}:${VARIABLE_NAME} --reload --host 0.0.0.0 --port ${PORT} --forwarded-allow-ips='*'